source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'Pokedex' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Pokedex
  pod 'SnapKit', '~> 5.6.0'
  pod 'R.swift'
  pod 'Nuke'

  target 'PokedexTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PokedexUITests' do
    # Pods for testing
  end

end
